# Docker Compose override for development
# This file is automatically applied in development environments
version: '3.8'

services:
  # Development overrides for the main application
  app:
    build: 
      target: builder  # Use builder stage for development with hot reload
    environment:
      - NODE_ENV=development
      - DEBUG=bomberman:*
      - LOG_LEVEL=debug
    volumes:
      - .:/app  # Mount source code for hot reload
      - /app/node_modules  # Prevent overwriting node_modules
    command: npm run dev  # Development command with hot reload

  # Enable development tools
  redis-commander:
    profiles: []  # Remove development profile to always start

  pgadmin:
    profiles: []  # Remove development profile to always start

  # Development database with different settings
  postgres:
    environment:
      - POSTGRES_DB=bomberman_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

# Development volumes
volumes:
  postgres_dev_data:
    driver: local